# Generated by Django 4.2.6 on 2023-11-28 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 54, 34, 763608)),
        ),
        migrations.AddField(
            model_name='banners',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 54, 34, 763608)),
        ),
    ]
