# Generated by Django 4.2.6 on 2023-11-28 12:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_banners_enddate_banners_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 17, 57, 10, 336596)),
        ),
        migrations.AlterField(
            model_name='banners',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 57, 10, 336596)),
        ),
    ]
