# Generated by Django 4.2.6 on 2023-11-28 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_colorvarient_discount_and_more'),
        ('admin_panel', '0003_alter_banners_enddate_alter_banners_startdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colorvarient'),
        ),
        migrations.AlterField(
            model_name='banners',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 18, 6, 4, 769209)),
        ),
        migrations.AlterField(
            model_name='banners',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 18, 6, 4, 769209)),
        ),
    ]
