# Generated by Django 4.2.6 on 2023-11-28 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_banners_variant_alter_banners_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banners',
            name='enddate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 18, 15, 26, 406138)),
        ),
        migrations.AlterField(
            model_name='banners',
            name='startdate',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 18, 15, 26, 406138)),
        ),
    ]
