# Generated by Django 4.2.6 on 2023-11-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='expiration_date',
            field=models.DateField(),
        ),
    ]
