# Generated by Django 4.2.6 on 2023-11-12 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_coupons_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='minimum_purchase',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
