# Generated by Django 4.2.6 on 2023-11-13 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_remove_coupons_user_couponusage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='couponusage',
            old_name='customer',
            new_name='user',
        ),
    ]
