# Generated by Django 4.2.6 on 2023-11-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_rename_customer_couponusage_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='discount_type',
        ),
    ]
