# Generated by Django 4.2.6 on 2023-11-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_remove_address_is_primary_address_is_present'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
