# Generated by Django 4.2.6 on 2023-11-24 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0007_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 16, 9, 31, 111638)),
        ),
    ]
