# Generated by Django 4.2.6 on 2023-11-28 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0008_customuser_forget_password_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 17, 49, 17, 292752)),
        ),
    ]
