# Generated by Django 4.2.6 on 2023-11-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0012_alter_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 28, 20, 12, 33, 953800)),
        ),
    ]
