# Generated by Django 4.2.6 on 2023-12-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0013_alter_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(),
        ),
    ]
