# Generated by Django 4.2.6 on 2024-02-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0014_alter_customuser_otp_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='otp_expiry',
            field=models.DateTimeField(null=True),
        ),
    ]
