# Generated by Django 4.2.6 on 2023-11-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prod_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
