# Generated by Django 4.2.6 on 2023-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_prod_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_price',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
