# Generated by Django 4.2.6 on 2023-11-05 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlogin', '0005_remove_address_is_primary_address_is_present'),
        ('products', '0008_remove_product_discount_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.PositiveIntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Order confirmed', 'Order confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_date', models.DateField(blank=True, null=True)),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.colorvarient')),
            ],
        ),
    ]
