# Generated by Django 4.2.6 on 2023-11-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_orders_status_ordersitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersitem',
            name='status',
            field=models.CharField(default='Order confirmed', max_length=20),
        ),
    ]
