# Generated by Django 4.2.6 on 2023-11-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_ordersitem_modified_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
