# Generated by Django 4.2.6 on 2023-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
