# Generated by Django 4.2.6 on 2023-10-27 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_discounted_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
