# Generated by Django 4.2.6 on 2023-10-28 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.colorvarient'),
        ),
    ]
