# Generated by Django 4.2.6 on 2023-11-15 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colorvarient',
            name='discounted_price',
        ),
    ]
